#!/bin/bash -e
#
# init disk mount
#

function imount {
    local dev="${1}"
    mkfs.ext4 -v -m .1 -b 4096 ${dev}

    uid=$(blkid ${dev} | grep -o ': UUID="[^"]*"')
    uid=${uid:2}
    uid=${uid//\"/}
    sed -i "\\^${data}^d" /etc/fstab
    echo "${uid} ${data} ext4 defaults 0 2" \
        | tee -a /etc/fstab

    mkdir -p ${data}
    touch ${data}/WARNING
    chown ${devops}:${devops} ${data}
    mount ${data}
    chown ${devops}:${devops} ${data}
}
